
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ab2b17fe-a4ce-4fc1-a380-f31e908953a6"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a1",
    "account_id_to": "a2",
    "amount": 50.0
}

###

GET http://localhost:8081/balances/a1 HTTP/1.1
