
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ab2b17fe-a4ce-4fc1-a380-f31e908953a6"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "93a397c6-be5e-4031-99eb-5a1452d3999f",
    "account_id_to": "363319f5-55fe-4ee9-bcae-947b7b3a3ab2",
    "amount": 100.0
}